[project]
name = "course-crusher"
version = "0.1.0"
description = "Command-line Jac project"
entry-point = "main"
kind = "cli"
jac-version = "==0.37.23"

[dependencies]

[dev-dependencies]
watchdog = ">=3.0.0"
