[project]
name = "course-crusher"
version = "0.1.0"
description = "Command-line Jac project"
entry-point = "main"
kind = "cli"
jac-version = "==0.37.23"

[dependencies]
google-auth = "~=2.60"
google-auth-oauthlib = "~=1.5"
requests = "~=2.34"

[dev-dependencies]
watchdog = ">=3.0.0"
